apiVersion: v1
kind: Service
metadata:
  name: my-orders
spec:
  selector:
    app: my-orders
  ports:
    - name: orders
      port: 8080
      targetPort: 8080
    - name: rabbitmq
      port: 15672
      targetPort: 15672
